#!/bin/bash
/show/description "Add dropbox upload support"
/system/downloadFile https://raw.github.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh /usr/local/bin/dropbox_uploader.sh
chmod +x /usr/local/bin/dropbox_uploader.sh

